title: Logan Johnson Portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until next key
  Game Development Portfolio for Logan Johnson. Showcasing Garry's Mod, Project Warfront, Unity, and Unreal Engine 5 projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loganjohnson.github.io" # the base hostname & protocol for your site
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed
  load_paths:
    - assets
minima:
  skin: null
  include_css: ["/assets/main.css"]
